
# hyper parameter
n_epoch: 400
inst_list: ['drums', 'bass', 'piano', 'guitar', 'residuals']

# data
dataset_dir: "/nas03/assets/Dataset/slakh"
n_dataset_test: 1000
batch_train: 64
batch_test: 64
num_workers: 8
pin_memory: true

datasetname: "slakh"
load_using_librosa: False
mix_minus_inst: False
test_psd_mine: False

mel: True
n_mels: 259
mono: True
f_size: 2048
hop_length: 512
seconds_psd_train: 3
seconds_psd_valid: 10
seconds_psd_test: 10
offset_psd_train: 1.5
offset_psd_valid: 5.0
offset_psd_test: 10.0
seconds_triplet_train: 3
seconds_triplet_valid: 3
#seconds_triplet_test: 10
offset_triplet_train: 1.5
offset_triplet_valid: 1.5
#offset_triplet_test: 10.0
seconds_c32_train: 3
seconds_c32_valid: 10
seconds_c32_test: 10
offset_c32_train: 1.5
offset_c32_valid: 5.0
offset_c32_test: 10.0
sr: 44100
db: True

# model
target: model.UNetForTriplet_2d_de5_to1d640
#target: model.UNetForTriplet_2d_de1_to1d640
#target: model.UNetForTriplet_to1d640_1dde5
#target: model.UNetForTriplet_to1d640_1dde1_embnet
#target: model.UNetForTriplet_2d_de5_to1d640_addencoder2
#target: model.NNetForTriplet
to1d_mode: "mean_linear"
#to1d_mode: "meanstd_linear"
order: "timefreq"
#order: "freqtime"
#order: "bilstm"
margin: 0.2
# monitor
#monitor_es: "Valid/knn_avr"
#monitor_es: "Valid/loss_all"
monitor_es: "Valid/knn_avr"
monitor_mode_es: "max"
#monitor_mode_es: "min"
#monitor_sch: "train/loss_mix"
#monitor_mode_sch: "min"
# rate of loss
triplet_rate: 1
unet_rate: 0
recog_rate: 0.01
# pretrain32
#ckpt_model_path: /home/imamura23/nas02home/outputs/pretrain/runs/2023-11-07/01-11-14/checkpoints/epoch_053.ckpt
# pretrain mel=259
#ckpt_model_path: /home/imamura23/nas02home/outputs/pretrain/runs/2023-11-07/00-58-42/checkpoints/epoch_016.ckpt
ckpt_model_path: /nas02/homes/imamura23-1000067/outputs/pretrain/runs/2023-11-15/15-31-05/checkpoints/epoch_027.ckpt
# pretrain mel=128
#ckpt_model_path: /nas02/homes/imamura23-1000067/outputs/pretrain/runs/2023-11-15/09-21-27/checkpoints/epoch_168.ckpt
# unet
#ckpt_model_path: /nas02/homes/imamura23-1000067/outputs/triplet_with_unet/runs/2023-11-11/14-22-12/checkpoints/epoch_025.ckpt
#ckpt_model_path: /nas02/homes/imamura23-1000067/outputs/triplet_with_unet/runs/2023-11-10/11-04-28/checkpoints/epoch_026.ckpt
#ckpt_model_path: /nas02/homes/imamura23-1000067/outputs/triplet_with_unet/runs/2023-11-01/09-41-24/checkpoints/epoch_028.ckpt
#ckpt_model_path: null

# path
output_dir: ${paths.output_dir}
