# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/tensorboard/"
  name: "lightning_logs"
  log_graph: False
  default_hp_metric: True
  prefix: ""
  # version: ""